### ISSUE TITLE
Function-based Component API (boilerplates)

### ISSUE THREAD

**Issue by pauloevpr** [vuejs/rfcs#74] opened 2019-07-23 06:27 UTC
Going straight to the point: The proposed Function-based Component API is just incredible! I used to hate it (I was excited about the dropped Class-based API). Now that I have the chance to look into it, I love it!

There is just one single thing that bothers me. It is how we have to end `setup()` with a `return` including everything we want to expose. It feels like writing boilerplate code, and it is really easy to forget to include something. That is especially true with large components - it can get a little hard to read ([other users](https://github.com/vuejs/rfcs/issues/54#issuecomment-506833838) seem to agree). 

Chances are I am not the only one with such concerns. Take the [todomvc.vue](https://gist.github.com/yyx990803/762ec427882a61be3e4affe02f8af555#file-todomvc-vue) example for instance. Computeds and methods are grouped together (probably as an attempt to improve readability), which sadly resembles a lot the old API.

How does the team see this issue? Are there any plans to improve that? (perhaps by returning everything within `setup()` somehow?)

**Comment by nekosaur** [comment] 2019-07-23 06:43
There has already been a discussion on implicitly returning from `setup()` here <https://github.com/vuejs/rfcs/pull/69>

**Comment by pauloevpr** [comment] 2019-07-23 06:51
Thank you for that. It seems #69 was dropped. Should I conclude the team has no intentions to tackle this issue?

**Comment by posva** [comment] 2019-07-23 07:05
Duplicate of #69

**Closed by posva** 2019-07-23 07:05 UTC

**Comment by yyx990803** [comment] 2019-07-23 15:18
Personally, I think the return statement serves as a centralized place to be explicit about what we are exposing to the template. i.e. anything you see in the template, you should be able to locate it in the return statement, and then trace its implementation details from there. This ensures you have a straightforward way to follow through code (especially when the code is not written by yourself). It also gives you control over what should or should not be exposed to the template.

I agree this can be somewhat verbose. One way to potentially mitigate that is by grouping different features under namespaces - i.e. split a big component into a number of composition functions, each returning an object of the properties that should be exposed, and access them in the template as nested properties:

``` js
setup() {
  const featureA = useFeatureA()
  const featureB = useFeatureB()

  return {
    // no spreading here, just access them as `featureA.xxx` in the template
    featureA,
    featureB
  }
}
```

**Comment by thecrypticace** [comment] 2019-07-23 22:06
I was wondering if that was actually going to work. Does this mean that `featureA.xyz` could be a method or that `featureB.foobar` could be a computed property?

**Comment by pauloevpr** [comment] 2019-07-24 06:43
> the return statement serves as a centralized place to be explicit about what we are exposing to the template

What if you don't want to be explicit? Up to now, Vue developers never had to worry about what is exposed to the template. We have now an additional step to remember, and probably an additional point of failure. Plus, exposing unnecessary things does not break anything, but forgetting to add something to `return` surely does. And that happens quite often (at least to me). 

I understand this might seem like a minor issue at first. However, as you start using the Function API for real on a daily bases, you realize how annoying the explicit returning becomes. It really feels like boilerplate. I am surprised that Implicit/automatic exposure was put aside so quickly.

**Comment by yyx990803** [comment] 2019-07-24 18:47
FYI, there's nothing that prevents a userland solution to this - it should be fairly straightforward to write a Babel plugin that automatically inserts a return statement with an object containing all the variables in the `setup()` function scope. Could be interesting to see how the trade-off plays out. However I don't think we should make that the default.

**Comment by pauloevpr** [comment] 2019-07-24 20:27
What about Vetur? I wonder if that solution would still allow intelliSense for template interpolation.

**Comment by pauloevpr** [comment] 2019-08-07 21:01
I finally found an efficient way to help me to remember to include everything in the `return` statement. Typescript compiler can raise an error if unused local variables are present. Those are the variables which are usually missing from the `return` statement.

To enable the error check, just add this line to your `tsconfig.json`:

```json
{
    "compilerOptions": {
        "noUnusedLocals": true
    }
}
```
